const assert = require('chai').assert,
      config = require('../askkodiakrc.json'),
      askKodiak = require('../../index.js');

askKodiak.init(config.gid, config.key, config.url);

describe('Product Codes', function () {
  it('all', function (done) {
    askKodiak.getRefDataProductCodes().then(function (res) {
      var expect = {
        'ACCT': 'Accountants Professional',
        'ACHE': 'Accident and Health',
        'AGENTS': 'Insurance Agents',
        'AGLIA': 'Agriculture Liability',
        'AGPP': 'Agriculture Scheduled and Unscheduled Personal Property',
        'AGPR': 'Agriculture Property',
        'AIRC': 'Aircraft',
        'AIRPFB': 'Airport and Fixed Base Operator',
        'APKGE': 'Agriculture Package',
        'APROD': 'Aircraft Products Liability',
        'ARCH': 'Architects Professional',
        'ARVP': 'Accounts Receivable/Valuable Papers',
        'ATV': 'All Terrain Vehicles',
        'AUTOB': 'Automobile - Business',
        'AUTOP': 'Automobile - Personal',
        'AVPKG': 'Aviation Package',
        'BAILEE': 'Bailee',
        'BANDM': 'Boiler and Machinery',
        'BIZTRV': 'Business Travel',
        'BMISC': 'Miscellaneous Bond',
        'BOAT': 'Watercraft',
        'BOP': 'Business Owners Policy',
        'BOPGL': 'Business Owners Policy Liability',
        'BOPPR': 'Business Owners Policy Property',
        'CAVN': 'Commercial Aviation',
        'CCAR': 'Automobile - Collector',
        'CEQFL': 'Contractor\'s Equipment Floater',
        'CFIRE': 'Commercial Fire',
        'CFRM': 'Farm Owners',
        'CGL': 'Commercial General Liability',
        'COMAR': 'Commercial Articles',
        'COMR': 'Ocean Marine',
        'CONDO': 'Condominium',
        'CONTR': 'Contract',
        'CPKGE': 'Commercial Package',
        'CPMP': 'Commercial Multi Peril',
        'CRIM': 'Crime',
        'CRIME': 'Crime (includes Burglary)',
        'CYBER': 'Cyber Liability',
        'DFIRE': 'Dwelling Fire',
        'DISAB': 'Disability',
        'DO': 'Directors And Officers',
        'DRONE': 'Drone',
        'EDP': 'Computers/Electronic Data Processing',
        'EL': 'Employers Liability',
        'EO': 'Errors and Omissions',
        'EPLI': 'Employment Practices Liability Insurance',
        'EQ': 'Earthquake',
        'EQLIA': 'Equine Liability',
        'EQPBD': 'Equipment Breakdown',
        'EQPFL': 'Equipment Floater',
        'EVENT': 'Special Event',
        'EXLIA': 'Excess Liability',
        'FEB': 'Funeral Expense',
        'FIDTY': 'Fidelity',
        'FIDUC': 'Fiduciary',
        'FINEA': 'Fine Arts',
        'FLOOD': 'Flood',
        'GARAG': 'Garage and Dealers',
        'GL': 'General Liability',
        'GLASS': 'Glass',
        'HANG': 'Private Hangar',
        'HBB': 'Home Based Business',
        'HLTH': 'Health',
        'HOME': 'Homeowners',
        'IFRD': 'Identity Fraud',
        'INBR': 'Installation/Builders Risk',
        'INMAR': 'Inland Marine',
        'INMRC': 'Inland Marine (commercial)',
        'INMRP': 'Inland Marine (personal)',
        'INTER': 'Internet Liability',
        'JUDCL': 'Judicial',
        'KIDRA': 'Kidnap and Ransom',
        'LAND': 'Vacant Land',
        'LANDLORD': 'Landlord',
        'LAWYERS': 'Lawyers Professional',
        'LICPT': 'License and Permit',
        'LIFE': 'Life',
        'LL': 'Liquor Liability',
        'LMORT': 'Livestock Mortality',
        'LSTIN': 'Lost Instrument',
        'MEDPROF': 'Media Professional',
        'MHOME': 'Mobile Homeowners',
        'MMAL': 'Medical Malpractice',
        'MPL': 'Medical Professional Liability',
        'MTRCR': 'Motor Carrier',
        'MTRTK': 'Motor Truck Cargo',
        'Motorcycle': 'Motorcycle',
        'NWFGR': 'New Financial Guarantee',
        'OLIB': 'Other Liability',
        'OPCAR': 'Open Cargo',
        'PAPER': 'Valuable papers',
        'PCRFT': 'Personal Watercraft (other than boat)',
        'PET': 'Pet',
        'PHYS': 'Physicians and Surgeons',
        'PL': 'Professional Liability',
        'PLMSC': 'Miscellaneous Professional Liability',
        'PPKGE': 'Personal Package',
        'PROPC': 'Commercial Property',
        'PROPM': 'Miscellaneous Property',
        'PTRL': 'Trailer (personal)',
        'PUBOF': 'Public Official',
        'RECV': 'Recreational Vehicles',
        'RENT': 'Renters',
        'RIDE': 'Ride Sharing',
        'SCAP': 'Small Commercial Package',
        'SCHPR': 'Scheduled Property',
        'SFRNC': 'Small Farm/Ranch',
        'SIGNS': 'Signs',
        'SMP': 'Special Multi-Peril',
        'SNOW': 'Snowmobiles',
        'STERM': 'Short Term Rental',
        'SURE': 'Surety',
        'TECH': 'Technology',
        'TRADE': 'Trade Credit',
        'TRANS': 'Transportation',
        'TRUCK': 'Truckers',
        'UMBRC': 'Umbrella - Commercial',
        'UMBRP': 'Umbrella (personal)',
        'WCMA': 'Workers Comp Marine',
        'WHSEL': 'Warehouse Legal Liability',
        'WIND': 'Wind Policy',
        'WORK': 'Workers Compensation',
        'WORKP': 'Workers Compensation Participating',
        'WORKV': 'Workplace Violence',
        'YACHT': 'Yacht'
      };

      assert.deepEqual(res, expect);
      done();
    });
  });
});
